{% set name = "bioimageio.spec" %}
{% set version = "0.4.9.post5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bioimageio.spec-{{ version }}.tar.gz
  sha256: 1b8e20be79a0f7e78c8dc1a7a2984646d9bcaeb811386a45de0806fc7757cc46

build:
  number: 0
  noarch: python
  entry_points:
    - bioimageio = bioimageio.spec.__main__:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - imageio >=2.5
    - marshmallow >=3.6.0,<4.0
    - marshmallow-jsonschema
    - marshmallow-union
    - packaging >=17.0
    - python >=3.7
    - python-stdnum
    - pyyaml >=5.2
    - requests
    - ruamel.yaml
    - tqdm
    - typer
    - typing-extensions

test:
  imports:
    - bioimageio
    - bioimageio.spec
  commands:
    - pip check
    - bioimageio --help
  requires:
    - pip

about:
  home: https://github.com/bioimage-io/spec-bioimage-io
  summary: Parser and validator library for BioImage.IO specifications
  dev_url: https://github.com/bioimage-io/spec-bioimage-io
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - constantinpape
    - FynnBe
    - k-dominik
    - oeway
